version: '3'
services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    image: sancoz
    container_name: php_sancoz
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - /home/miguel/Documents/pruebas/back-sancoz:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/php.ini
      - ./logs:/usr/local/var/log/

    networks:
      - app-network

  web:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: sancoz_backend
    container_name: sancoz_backend
    ports:
      - "4201:80"
      - "443:443"
    volumes:
      - /home/miguel/Documents/pruebas/back-sancoz:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf

    networks:
      - app-network
    depends_on:
      - php

  mariadb:
    image: mysql:latest
    container_name: sancoz_mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret

    volumes:
      - /home/miguel/Documents/datas/test_databases/sancoz:/var/lib/mysql

    # Si usas Windows crea un volumen antes
    # y luego descomenta las siguientes l√≠neas
    #volumes:
    #- base_datos:/var/lib/mysql

    ports:
      - "3316:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.27.0.0/16
          #docker-compose v3+ do not use ip_range
          #ip_range: 172.22.1.0/24